version: 2
jobs:
  build:
    docker:
      - image: quay.io/3scale/s2i-openresty-centos7:luarocks-build
    steps:
      - checkout
      - run: luarocks install busted
      - run: luarocks path --bin
      - run: ls -l .
      - run: bin/busted
